// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace SushiDelivery.DAL.Models
{
    /// <summary>
    /// Model for saving <see>Categories</see> enum to dictionary table in db.
    /// </summary>
    public partial class Category
    {
        // TODO: Add custom migration to populate dictionary table from Categories enum.
        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(256)]
        public string Name { get; set; }
    }
}
