// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace SushiDelivery.DAL.Models.Configurations
{
    public partial class ConfigurationBase 
    {
        protected void ConfigureBase(EntityTypeBuilder entity)
        {
            entity.Property<DateTimeOffset>(nameof(IEntityBase.CreatedDate)).HasDefaultValueSql("getutcdate()").HasColumnOrder(101);
            entity.Property<DateTimeOffset>(nameof(IEntityBase.UpdatedDate)).HasDefaultValueSql("getutcdate()").HasColumnOrder(102);
            entity.Property<DateTimeOffset>(nameof(IEntityBase.DeletedDate)).HasDefaultValueSql("getutcdate()").HasColumnOrder(103);
            entity.Property<bool>(nameof(IEntityBase.IsDeleted)).HasDefaultValueSql("0").HasColumnOrder(104);
            entity.Property<byte[]>(nameof(IEntityBase.TimeStamp))
            .IsRowVersion()
            .IsConcurrencyToken()
            .HasColumnOrder(105);
        }
    }
}
